# Generated by Django 3.1.1 on 2020-10-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('คณิตศาสตร์', 'คณิตศาสตร์'), ('วิทยาศาสตร์', 'วิทยาศาสตร์'), ('ศิลป', 'ศิลป'), ('ภาษาอังกฤษ', 'ภาษาอังกฤษ'), ('ฟิสิกส์', 'ฟิสิกส์'), ('ชีววิทยา', 'ชีววิทยา')], default='คณิตศาสตร์', max_length=200)),
                ('student_name', models.CharField(max_length=200)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
    ]
