# Generated by Django 3.1.1 on 2020-10-06 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hellomobileapp', '0002_auto_20201006_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='subject',
            new_name='devices',
        ),
    ]
