# Generated by Django 3.1.1 on 2020-10-06 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hellomobileapp', '0003_auto_20201006_1421'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Report',
            new_name='ReportList',
        ),
    ]
