# Generated by Django 3.1.1 on 2020-10-06 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hellomobileapp', '0004_auto_20201006_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportlist',
            old_name='price',
            new_name='pricesale',
        ),
    ]
