# Generated by Django 3.1.1 on 2020-10-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hellomobileapp', '0005_auto_20201006_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportlist',
            name='code',
            field=models.IntegerField(default=0),
        ),
    ]
