# Generated by Django 3.1.1 on 2020-10-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hellomobileapp', '0006_reportlist_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportlist',
            name='code',
            field=models.IntegerField(default=13),
        ),
    ]
