# Generated by Django 3.1.1 on 2020-10-06 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hellomobileapp', '0007_auto_20201006_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('Bronze', 'ทองแดง'), ('Silver', 'เงิน'), ('Gold', 'ทอง'), ('Diamond', 'เพชร')], default='Bronze', max_length=100)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_id', models.CharField(max_length=200)),
                ('customer_tel', models.CharField(blank=True, max_length=200, null=True)),
                ('othercontact_name', models.CharField(blank=True, max_length=200, null=True)),
                ('othercontact_tel', models.CharField(blank=True, max_length=200, null=True)),
                ('other', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='reportlist',
            name='code',
            field=models.IntegerField(default=0),
        ),
    ]
