# Generated by Django 3.1.1 on 2020-10-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hellomobileapp', '0008_auto_20201007_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportlist',
            name='customer_id',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reportlist',
            name='devices',
            field=models.CharField(choices=[('Apple', 'แอปเปิ้ล'), ('Samsung', 'ซัมซุง'), ('Huawei', 'หัวเว่ย'), ('OPPO', 'ออปโป'), ('VIVO', 'วีโว'), ('Xiaomi', 'เสียวหมี่')], default='Apple', max_length=100),
        ),
    ]
