# Generated by Django 3.1.1 on 2020-10-06 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hellomobileapp', '0009_auto_20201007_0304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportlist',
            name='customer_id',
        ),
    ]
