# Generated by Django 3.1.1 on 2020-10-07 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hellomobileapp', '0010_remove_reportlist_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportlist',
            name='device_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
