# Generated by Django 3.1.1 on 2020-10-07 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hellomobileapp', '0011_reportlist_device_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportlist',
            old_name='device_name',
            new_name='model_name',
        ),
    ]
