# Generated by Django 3.1.1 on 2020-10-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hellomobileapp', '0013_auto_20201007_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='allcustomer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='customerphoto'),
        ),
    ]
