# Generated by Django 3.1.1 on 2020-10-07 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hellomobileapp', '0014_allcustomer_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('Bronze', 'ทองแดง'), ('Silver', 'เงิน'), ('Gold', 'ทอง'), ('Diamond', 'เพชร')], default='Bronze', max_length=100)),
                ('document_name', models.CharField(max_length=100)),
                ('document', models.FileField(upload_to='alldocument')),
                ('other', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photoprofile', models.ImageField(blank=True, default='default.png', null=True, upload_to='photo_profile')),
                ('usertype', models.CharField(blank=True, default='customer', max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
