# Generated by Django 3.1.1 on 2020-10-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hellomobileapp', '0015_document_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('Bronze', 'ทองแดง'), ('Silver', 'เงิน'), ('Gold', 'ทอง'), ('Diamond', 'เพชร')], default='ม.1', max_length=100)),
                ('document_name', models.CharField(max_length=100)),
                ('document', models.FileField(upload_to='alldocument')),
                ('other', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
