# Generated by Django 3.1.1 on 2020-10-08 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hellomobileapp', '0016_auto_20201007_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentupload',
            name='level',
            field=models.CharField(choices=[('Bronze', 'ทองแดง'), ('Silver', 'เงิน'), ('Gold', 'ทอง'), ('Diamond', 'เพชร')], default='Bronze', max_length=100),
        ),
    ]
