# Generated by Django 3.1.1 on 2020-10-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hellomobileapp', '0018_auto_20201009_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportlist',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
