# Generated by Django 3.1.1 on 2020-10-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hellomobileapp', '0019_auto_20201009_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportlist',
            name='status',
            field=models.CharField(choices=[('Complte', 'สำเร็จ'), ('Not Complete', 'ยังไม่สำเร็จ')], default='Complete', max_length=100),
        ),
    ]
