# Generated by Django 3.1.1 on 2020-10-09 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hellomobileapp', '0020_auto_20201009_1759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='photoprofile',
            new_name='profile_image',
        ),
    ]
