# Generated by Django 3.1.1 on 2020-10-09 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hellomobileapp', '0021_auto_20201009_2329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_image',
            new_name='photoprofile',
        ),
    ]
