# Generated by Django 3.1.1 on 2020-10-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hellomobileapp', '0023_auto_20201010_0353'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
    ]
