# Generated by Django 3.1.1 on 2020-10-10 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hellomobileapp', '0024_contactus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='email',
            new_name='emailhelp',
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='name',
            new_name='namehelp',
        ),
    ]
