# Generated by Django 3.1.1 on 2020-10-10 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hellomobileapp', '0025_auto_20201010_2157'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
    ]
