# Generated by Django 3.1.1 on 2020-10-11 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hellomobileapp', '0031_auto_20201011_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportlist',
            name='code',
            field=models.IntegerField(default=10001),
        ),
    ]
