# Generated by Django 3.1.1 on 2020-10-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hellomobileapp', '0032_reportlist_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportlist',
            name='id',
        ),
        migrations.AlterField(
            model_name='reportlist',
            name='code',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
