# Generated by Django 3.1.1 on 2020-10-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hellomobileapp', '0033_auto_20201011_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportlist',
            name='code',
        ),
        migrations.AddField(
            model_name='reportlist',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
