# Generated by Django 3.1.1 on 2020-10-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hellomobileapp', '0037_contact_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportlist',
            name='brand',
            field=models.CharField(max_length=100),
        ),
    ]
