# Generated by Django 3.1.1 on 2020-10-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hellomobileapp', '0038_auto_20201011_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportlist',
            name='brand',
            field=models.CharField(choices=[('Apple', 'แอปเปิ้ล'), ('Samsung', 'ซัมซุง'), ('Huawei', 'หัวเว่ย'), ('OPPO', 'ออปโป'), ('VIVO', 'วีโว'), ('Xiaomi', 'เสียวหมี่')], default='Apple', max_length=100),
        ),
    ]
