# Generated by Django 3.1.1 on 2020-10-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hellomobileapp', '0039_auto_20201011_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportlist',
            name='id',
        ),
        migrations.AddField(
            model_name='reportlist',
            name='cus_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
