# Generated by Django 3.0.5 on 2020-11-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hellomobileapp', '0040_auto_20201011_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportlist',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='statusphoto'),
        ),
    ]
