# Generated by Django 3.0.5 on 2020-11-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hellomobileapp', '0041_reportlist_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportlist',
            name='photo',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='photo_profile'),
        ),
    ]
