# Generated by Django 3.0.5 on 2020-11-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hellomobileapp', '0042_auto_20201105_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportlist',
            name='photo',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='repair'),
        ),
    ]
