# Generated by Django 3.0.5 on 2020-11-05 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hellomobileapp', '0043_auto_20201105_2122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportlist',
            old_name='photo',
            new_name='photorepair',
        ),
    ]
