# Generated by Django 3.1.3 on 2021-02-18 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hellomobileapp', '0044_auto_20201105_2157'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllCustomer',
        ),
        migrations.DeleteModel(
            name='DocumentUpload',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='ReportList',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
